import "./globals.css";
import Footer from "@/components/Footer";
import Navber from "@/components/Navber";
import { GoogleTagManager } from "@next/third-parties/google";
import Script from "next/script";

export const metadata = {
  title: "Idea To Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Google Tag Manager */}
        {/* <GoogleTagManager gtmId="GTM-N92HF5H2" /> */}

        {/* Facebook Pixel */}
        <Script
          id="facebook-pixel"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '883250121313567');
              fbq('track', 'PageView');
            `,
          }}
        />

        {/* Facebook Pixel NoScript */}
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=883250121313567&ev=PageView&noscript=1"
          />
        </noscript>

        <Navber />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
