import "./globals.css";
import Footer from "@/components/Footer";
import Navber from "@/components/Navber";
import { GoogleTagManager } from "@next/third-parties/google";

export const metadata = {
  title: "Idea To Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Google Tag Manager */}
        <GoogleTagManager gtmId="GTM-N92HF5H2" />

        <Navber />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
